name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install deps
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: test
        run: |
          python -m pytest --cov=catchment.models tests/test_models.py
